[package]
name = "year_proc_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2"
quote = "1"
anyhow = "1"
proc-macro2 = "1" 

[lib]
proc-macro = true
